server:
  port: 8080
spring:
  datasource:
    platform: mariadb
    url: jdbc:mariadb:failover//45.62.230.34/estoque
    username: root
    password: master@root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: SpringBootJpaHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update